conforming to MVVM
AmandaApolinario/CatInfo pull request #2
Opened 2022-08-30 18:03 UTC by AmandaApolinario

2022-08-30 21:00 UTC, jefnazario requested changes

2022-08-30 21:00 UTC, jefnazario commented on GatinhoInfo/Controllers/TableViewController.swift
> +    private var viewModel = TableViewModel()
Essa variável foi declarada como `var`, mas ela poderia ser `let`?

2022-08-30 21:00 UTC, jefnazario commented on GatinhoInfo/Controllers/TableViewController.swift
> +        self.viewModel.fetchBreeds()
Você tem usado o `self.` em todos os locais, porém o uso dele não é mandatório, tem algum motivo em específico para você usar?

2022-08-30 21:00 UTC, jefnazario commented on GatinhoInfo/Controllers/TableViewController.swift
> +
Excelente essa separação do código por `extension`, parabéns 🎉

2022-08-30 21:00 UTC, jefnazario commented on GatinhoInfo/ViewModel/TableViewModel.swift
> +    func item(_ indexPath: IndexPath) -> String {
O nome desse método pode ser mais específico, para representar o que ele realmente faz.

2022-08-31 12:01 UTC, AmandaApolinario commented on GatinhoInfo/Controllers/TableViewController.swift
> +    private var viewModel = TableViewModel()
Poderia mesmo

2022-08-31 12:02 UTC, AmandaApolinario commented on GatinhoInfo/Controllers/TableViewController.swift
> +        self.viewModel.fetchBreeds()
Não tem, eu achei que fosse necessário porque no artigo que vc mandou eles usam, ai imaginei que precisasse. Vou pesquisar sobre pra entender

2022-08-31 13:00 UTC, merged